name: "Container Build"

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  platforms: "linux/amd64"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        ghidra-version:
          - "latest"
          - "10.2.2"
          - "10.1.5"
          - "10.0.4"
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get short SHA ref
        id: vars
        run: |
          echo "sha_short=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        if: ${{ contains(env.PLATFORMS, 'arm') }}
        with:
          platforms: "arm,arm64"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.platforms }}

      - name: Login to GHCR
        id: login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavour: |
            suffix=-${{ matrix.ghidra-version }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=${{ env.sha_short }}-${{ matrix.ghidra-version }},suffix=
            type=raw,value=${{ matrix.ghidra-version }},suffix=

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          tags: |
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.ghidra-version }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
              GHIDRA_VERSION=${{ matrix.ghidra-version }}

      - name: Build and Push Versioned Tags
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          platforms: ${{  env.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=build-${{ env.IMAGE_NAME }}-${{ matrix.ghidra-version }}
          cache-to: type=gha,mode=max,scope=build-${{ env.IMAGE_NAME }}-${{ matrix.ghidra-version }}
          build-args: |
            GHIDRA_VERSION=${{ matrix.ghidra-version }}
